version: "3.8"
services:
  model2:
    build:
      context: ./model2
      dockerfile: Dockerfile
    container_name: md_model2
    volumes:
      - ./data:/data:rw
      - ./model2:/app:rw
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    tty: true
